# Generated by Django 4.2.27 on 2025-12-18 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("surveillance", "0002_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monitor_mode",
                    models.CharField(
                        choices=[
                            ("always", "Always Monitor"),
                            ("after_hours", "After Hours Only"),
                            ("custom", "Custom Hours"),
                        ],
                        default="always",
                        help_text="When to monitor: always, after hours only, or custom hours",
                        max_length=20,
                    ),
                ),
                (
                    "active_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="Start time for active hours (required if monitor_mode is 'after_hours' or 'custom')",
                        null=True,
                    ),
                ),
                (
                    "active_hours_end",
                    models.TimeField(
                        blank=True,
                        help_text="End time for active hours (required if monitor_mode is 'after_hours' or 'custom')",
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Timezone for active hours (e.g., 'America/New_York', 'UTC')",
                        max_length=50,
                    ),
                ),
                (
                    "confidence_threshold",
                    models.FloatField(
                        default=0.6,
                        help_text="Default confidence threshold (0.0 to 1.0)",
                    ),
                ),
                (
                    "frame_skip",
                    models.IntegerField(
                        default=5,
                        help_text="Number of frames to skip between detections (performance optimization)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        help_text="Camera-level override (leave blank if this is a user default)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_config",
                        to="surveillance.camera",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User-level default config (leave blank if this is a camera override)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Detection Config",
                "verbose_name_plural": "Detection Configs",
            },
        ),
        migrations.CreateModel(
            name="DetectionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_class",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("bicycle", "Bicycle"),
                            ("car", "Car"),
                            ("motorcycle", "Motorcycle"),
                            ("bus", "Bus"),
                            ("truck", "Truck"),
                            ("backpack", "Backpack"),
                            ("handbag", "Handbag"),
                            ("suitcase", "Suitcase"),
                            ("knife", "Knife"),
                            ("bottle", "Bottle"),
                            ("cell phone", "Cell Phone"),
                            ("laptop", "Laptop"),
                        ],
                        help_text="YOLO COCO object class name",
                        max_length=50,
                    ),
                ),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("HIGH", "High Threat"),
                            ("MEDIUM", "Medium Threat"),
                            ("LOW", "Low Threat"),
                            ("IGNORE", "Ignore"),
                        ],
                        default="MEDIUM",
                        help_text="Threat level for this object class",
                        max_length=10,
                    ),
                ),
                (
                    "should_alert",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to send alerts for this object class",
                    ),
                ),
                (
                    "min_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum confidence threshold for this rule (overrides config default if set)",
                        null=True,
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        help_text="Parent detection configuration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_rules",
                        to="surveillance.detectionconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detection Rule",
                "verbose_name_plural": "Detection Rules",
                "indexes": [
                    models.Index(
                        fields=["config", "object_class"],
                        name="surveillanc_config__698dab_idx",
                    )
                ],
                "unique_together": {("config", "object_class")},
            },
        ),
        migrations.AddIndex(
            model_name="detectionconfig",
            index=models.Index(fields=["user"], name="surveillanc_user_id_9e72b2_idx"),
        ),
        migrations.AddIndex(
            model_name="detectionconfig",
            index=models.Index(
                fields=["camera"], name="surveillanc_camera__e29175_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="detectionconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("camera__isnull", True)),
                fields=("user",),
                name="unique_user_default_config",
            ),
        ),
        migrations.AddConstraint(
            model_name="detectionconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("camera",),
                name="unique_camera_override_config",
            ),
        ),
    ]
